version: '3.5'

services:
  app:
    container_name: kangsunu-app
    image: kangsunu-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    #volumes:
    #  - .:/var/www/html
    #  - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
    #  - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - kangsunu_net
      
  db:
    container_name: kangsunu-db
    image: mariadb
    environment:
      MYSQL_DATABASE: kangsunu-db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    #volumes:
    #  - ./database/db_data:/var/lib/mysql
    #  - ./database/project_alumni.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - kangsunu_net
    
  phpmyadmin:
    container_name: kangsunu-pma
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    networks:
      - kangsunu_net


networks:
  kangsunu_net:
    external: false
    name: kangsunu_net